server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: proman-api

  datasource:
    url:
    username:
    password:

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
